### ISSUE TITLE
Invisible Fire

### ISSUE THREAD

**Issue by PhillipeEchtebaise** [gimicze/firescript#41] opened 2024-11-30 22:04 UTC
**Describe the bug**
Hello, I am having a problem with the fire script, in fact I was on the old version where there was no fire difficulty yet, and sirene included in the script, since I upgraded my ESX on the latest build and the script on its latest version, regularly on I die, crash, deco during or before/after a fire, when I come back I no longer see any, at times a simple deco reco after the extinction of all fire is enough, but generally it is necessary completely restart the server

**To be reproduced**
1. crash or leave during a fire in progress at the scene thereof
2. once reconnected, it is invisible
3. I have to /stopallfires and disconnect and reconnect to resolve the issues, or restart the entire server

**Expected behavior**
A solution, or an alternative, such as an interior update that wouldn't have the hassle? Or an update 2.0.2 with the aim of resolving the following issues.

**Server :**
 - Artifact: [e.g. 3258]
 - Script version: [e.g. 2.0.1]

**Comment by gimicze** [comment] 2024-12-01 09:12
Hello 👋 

Sorry to hear you're having such issues - this definitely shouldn't be happening! It's strange as I haven't changed anything regarding death/reconnect etc. synchronisation for a long time now - if there are problems, they should be present even when extinguishing the fires. I will definitely have a look to see whether I can reproduce this though. 

Few questions:
- what version did you use before updating to 2.0.1?
- does this happen every time you disconnect/die around an active fire?
- are there any errors/notifications in the console (both server and client) from firescript?

**Comment by PhillipeEchtebaise** [comment] 2024-12-01 11:29
Hello, 

thank you for your response,
The old version used was FIRE SCRIPT v1.7.6

No, this does not systematically occur after a death or crash, I will try to reproduce it to possibly give a more precise description of the problems.

We have also just made an infinity modification to one sync in order to check if it is not this.

And regarding the errors, I have none, I will try to check on the server console if it would be more talkative than the menu F8

**Comment by PhillipeEchtebaise** [comment] 2024-12-01 11:38
I placed 20 fires, the maximum. I decorated recce while 2 people were nearby. When I connected all the lights were invisible, and here is the error present in the F8.

^1SCRIPT ERROR: @firescript/client/fire.lua:173: attempt to perform arithmetic on a table value (local 'coords')^7
^3> fn^7 (^5@firescript/client/fire.lua^7:173)

**Comment by gimicze** [comment] 2024-12-01 14:38
Thank you for the details :-) I've found one part of code which I forgot to update since adding the "difficulty" system and should be causing this behaviour. I am not able to test the fix yet (will get back to it in the coming days), but in the meantime, you can test it yourself: Download [latest code ](https://github.com/gimicze/firescript/archive/refs/heads/main.zip) from main branch and replace files in firescript directory (you can keep your current 2.0.1 configs, but please back them up just in case).

**Comment by gimicze** [comment] 2024-12-01 17:52
I've just tried - fixed in cacbcce, released fix [version v2.0.2](https://github.com/gimicze/firescript/releases/tag/v2.0.2). I'll leave this issue open until you confirm you no longer have issues as well 😄

**Comment by PhillipeEchtebaise** [comment] 2024-12-02 01:58
I will try it shortly and you will get back to me as soon as possible.

**Comment by PhillipeEchtebaise** [comment] 2024-12-02 08:51
I have just carried out the first tests which are conclusive, the problems initially reported here are no longer present, I will keep you informed in the event of a new dispute during future tests on the server.

Thank you for your responsiveness and your help.

**Comment by gimicze** [comment] 2024-12-02 09:18
Thanks for reporting the issue!

**Closed by gimicze** 2024-12-02 09:18 UTC
Labels: bug, good first issue
